listen_addr = "127.0.0.1:9650"
# Replace with your node URL
wrpc_url = "wss://node:16110"
# false = testnet-10, true = mainnet
mainnet = false
# Guardian key backend (file path or hsm:ENV_VAR for HSM integrations)
key_path = "guardian.key"
# HTTP metrics port
http_port = 9651
# Log level for env_logger
log_level = "info"
# Optional path to persist guardian state
# state_path = "guardian_state.json"
